# 1.このテキストについて
### テキストの目的
数式演算ライブラリのNumPyに慣れる  
行列演算に慣れる

### どのように学ぶか
行列積の計算を手計算で行った後、スクラッチ実装することで理解を深めていきます。

# 2.行列積
以下のような行列A、Bを考えます。

$$
A =
\begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9 \\
\end{bmatrix},　
B =
\begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1 \\
\end{bmatrix}
$$

NumPyで表すと次のようになります。

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください

$$
A \times B =
\begin{bmatrix}
-1 \times 0 + 2 \times 0 + 3 \times 2 & -1 \times 2 + 2 \times 2 + 3 \times 9 & -1 \times 1 + 2 \times -8 + 3 \times -1 \\
4 \times 0 + -5 \times 0 + 6 \times 2 & 4 \times 2 + -5 \times 2 + 6 \times 9 & 4 \times 1 + -5 \times -8 + 6 \times -1 \\
7 \times 0 + 8 \times 0 + -9 \times 2 & 7 \times 2 + 8 \times 2 + -9 \times 9 & 7 \times 1 + 8 \times -8 + -9 \times -1 \\
\end{bmatrix}  
=
\begin{bmatrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48 \\
\end{bmatrix} 
$$

# 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください。

In [2]:
# np.matmul()
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [3]:
# np.dot()
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [4]:
# @演算子
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

《3種類の違い》

np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。

今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。
>If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

# 3.行列積のスクラッチ実装
np.matmul()やnp.dot()、または@演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。

# 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。


- 行列Aの(0,0)の要素$a_{0,0}$と行列Bの(0,0)の要素$b_{0,0}$を掛け合わせる
- 行列Aの(0,1)の要素$a_{0,1}$と行列Bの(1,0)の要素$b_{1,0}$を掛け合わせる
- 行列Aの(0,2)の要素$a_{0,2}$と行列Bの(2,0)の要素$b_{2,0}$を掛け合わせる
- それらの値を全て足し合わせる

数式で表すと
$$
\sum_{k=0}^{2}a_{0,k}b_{k,0}
$$
です。

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [5]:
count = 0
number = 0
ndarray = []
for i in range(a_ndarray.shape[0]):
    for j in range(b_ndarray.shape[1]):
        for k in range(a_ndarray.shape[1]):
            mult = a_ndarray[i][k] * b_ndarray[k][j]
            number += mult           
            count += 1
            if count == a_ndarray.shape[1]:
                ndarray.append(number)
                count = 0
                number = 0

ndarray = np.array(ndarray)
ndarray.reshape(a_ndarray.shape[0], b_ndarray.shape[1])

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である$3×3$の行列Cの各要素$c_{i,j}$は数式で表すと次のようになります。

$$
c_{i,j}=
\sum_{k=o}^{2}a_{i,k}b_{k,j}
$$

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス$i$や$j$を1増やすと、次の行や列に移ることができます。

In [6]:
def matrix_multiplication(a, b):
    count = 0
    number = 0
    ndarray = []
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                mult = a[i][k] * b[k][j]
                number += mult           
                count += 1
                if count == a.shape[1]:
                    ndarray.append(number)
                    count = 0
                    number = 0

    ndarray = np.array(ndarray)
    return ndarray.reshape(a.shape[0],b.shape[1])

In [7]:
matrix_multiplication(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 4.行列積が定義されない組み合わせの行列
次に以下のような例を考えます。

$$
D =
\begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
\end{bmatrix},
E =
\begin{bmatrix}
-9 & 8 & 7 \\
6 & -5 & 4 \\
\end{bmatrix}
$$


In [8]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

# 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [9]:
def matrix_multiplication(a, b):
    if a.shape[1] != b.shape[0]:
        print('第一引数の列数と第二引数の行数が異なる為、計算できません。')
        return
    count = 0
    number = 0
    ndarray = []
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                mult = a[i][k] * b[k][j]
                number += mult           
                count += 1
                if count == a.shape[1]:
                    ndarray.append(number)
                    count = 0
                    number = 0

    ndarray = np.array(ndarray)
    return ndarray.reshape(a.shape[0],b.shape[1])

In [10]:
matrix_multiplication(d_ndarray, e_ndarray)

第一引数の列数と第二引数の行数が異なる為、計算できません。


# 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [11]:
# e_ndarrayを転置した時の行列積を求める。(2*3)(3*2)
matrix_multiplication(d_ndarray, e_ndarray.T)

array([[ 46,  -4],
       [-34,  73]])

In [12]:
# 確認用
d_ndarray @ e_ndarray.T

array([[ 46,  -4],
       [-34,  73]])

In [13]:
# np.transpose()を使ってみる。
matrix_multiplication(d_ndarray, np.transpose(e_ndarray))

array([[ 46,  -4],
       [-34,  73]])

In [14]:
# d_ndarrayを転置した時の行列積を求める。(3*2)(2*3)
matrix_multiplication(d_ndarray.T, e_ndarray)

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])

In [15]:
# 確認用
d_ndarray.T @ e_ndarray

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])