# 1.このテキストについて

#### テキストの目的
- クラスを利用したコードを読み書きできるようにする

#### どのように学ぶか  
これまで使用してきたクラスを元にしてオブジェクト指向を理解していきます。

# 2.オブジェクト指向

これまでの課題では触れてきませんでしたが、StandardScalerやLinearRegressionのような クラス と呼ばれるものがPythonなどのプログラム言語では利用できます。


クラスの構文は、オブジェクト指向と呼ばれる考え方を利用したプログラミングの基本的な道具になります。


この課題ではこれまでに既に登場していたクラスを例に、クラスを活用することでどのようなことができるのかを見て学んでいきます。そして課題の後半ではStandardScalerのクラスをスクラッチで自作します。

# 3.scikit-learnの標準化クラス

scikit-learnに用意されている標準化を行うためのクラスStandardScalerを例に見ていきます。サンプルコードを用意しましたので、これを利用しながら理解していきます。


[sklearn.preprocessing.StandardScaler — scikit-learn 0.21.3 documentation](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)


《サンプルコード》

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


In [2]:
import numpy as np
import pandas as pd

# 【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。


Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

### 解答

### Pandas
- DataFrame
- Series

### matplotlib
- pyplot

### scikit-learn
- train_test_split
- DecisionTreeRegressor

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。


最低でもそれぞれ5つ以上答えてください

### 解答
#### メソッド
- head()
- describe()
- info()
- corr()
- isnull()

#### インスタンス
- columns
- index
- dtypes
- T
- values

## インスタンス変数をメソッドが利用
最終的に以下のようにして標準化を行います。


X_std = scaler.transform(X)


これはfitメソッドで計算したことでインスタンス変数mean_やvar_に保存されていた値を使い、Xを変換したということです。


このようにクラスには複数のメソッドやインスタンス変数が存在し、これらを組み合わせていろいろな機能を実現します。

# 【問題3】標準化クラスをスクラッチで作成
理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。


今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。


インスタンス変数を作成する際はself.mean_のようにselfを付けます。クラスの外からscaler.mean_と書いていたscalerの部分が自分自身を表すselfになっています。


《雛形》

In [3]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)
        
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [4]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


## 特殊メソッド
ソースコードの中に含まれる、まだ説明していない重要な部分が以下です。  
このような__init__というメソッドは、どのクラスにも共通して置かれる コンストラクタ と呼ばれるメソッドです。  

コンストラクタの動作を確認するためのサンプルコードを用意しました。コンストラクタは、インスタンス化が行われる時に自動的に実行されるという働きがあります。こういった特殊な動作をするメソッドを、 特殊メソッド と呼びます。  

《サンプルコード》

In [5]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8


# 【問題4】 四則演算を行うクラスの作成
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。


コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。


クラス名や説明文も適切に書き換えてください。

In [6]:
class ArithmeticOperations():
    """
    四則演算を行うクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):       
        # 型を判定する
        if type(value) == int or type(value) == float:
            self.value = value
            print("初期値{}が設定されました".format(self.value))
        else:
            # elseならTypeErrorを返す
            raise TypeError('数字以外が入力されました。数字のみを入力してください')
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    def sub(self, value2):
        """
        受け取った引数をself.valueから引く
        """
        self.value -= value2
    def mul(self, value2):
        """
        受け取った引数をself.valueに掛ける
        """
        self.value *= value2
    def div(self, value2):
        """
        受け取った引数をself.valueから割る
        """
        self.value /= value2

In [7]:
ao = ArithmeticOperations(10)
ao.add(10)
print(f'足し算: {ao.value}')

ao.sub(10)
print(f'引き算: {ao.value}')

ao.mul(10)
print(f'掛け算: {ao.value}')

ao.div(10)
print(f'割り算: {ao.value}')

初期値10が設定されました
足し算: 20
引き算: 10
掛け算: 100
割り算: 10.0


In [8]:
ao = ArithmeticOperations('a')

TypeError: 数字以外が入力されました。数字のみを入力してください